server:
  port: 8082
  servlet:
    context-path: /profile

spring:
  jpa:
    show-sql: true
  application:
    name: profile-service
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 12345678
